### ISSUE TITLE
数据集应该是什么样子的?

### ISSUE THREAD

**Issue by zhangbincheng1997** [fjxmlzn/RNN-SM#1]
'''
Read codeword file
-------------
input
    file_path
        The path to an ASCII file.
        Each line contains three integers: x1 x2 x3, which are the three codewords of the frame.
        There are (number of frame) lines in total. 
output
    the list of codewords
'''
直接将wav放在文件夹下无法正常运行.
报错信息:'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte

如题,是不是需要codewords文本才能运行?
另外,这部分是不是需要自己转换?

**Comment by fjxmlzn** [comment]
您好！

需要codeword文本文件。每行三个整数，代表该帧的三个码字。例如
1 2 3
4 5 6
7 8 9
10 11 12

wav到codeword文本文件的转换代码没有提供（由于代码版权原因），需要自己转换，抱歉。
